language: go
cache:
  apt: true
matrix:
  include:
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64
        /
      key_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
    - sourceline: deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64
        /
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libopenblas-dev
    - libgsl0-dev
    - liblapacke-dev
    - google-perftools
    - libgoogle-perftools-dev
    - graphviz
    - cmake
    - libmicrohttpd-dev
    - libssl-dev
    - libpci-dev
    - libhwloc-dev
    - libnuma-dev
    - libnccl2
    - cuda-cudart-dev-9-2
    - cuda-libraries-dev-9-2
    - cuda-cublas-dev-9-2
    - cuda-misc-headers-9-2
    - cuda-nvml-dev-9-2
    - cuda-cupti-9-2
    - libcudnn7
    - libcudnn7-dev
env:
  global:
  - CXX=g++-6
  - CC=gcc-6
  - CUDACXX=/usr/local/cuda-9.2/bin/nvcc
  - LD_LIBRARY_PATH=/usr/local/nvidia/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/nvvm/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64/stubs${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/targets/x86_64-linux/lib/stubs/:+:${LD_LIBRARY_PATH}}
  - LD_LIBRARY_PATH=/usr/local/cuda-9.2/extras/CUPTI/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
  - PATH=/usr/local/cuda-9.2/bin${PATH:+:${PATH}}
  - GODEBUG=cgocheck=0
  - CGO_CFLAGS="${CGO_CFLAGS} -I /usr/local/cuda-9.2/include -I/usr/local/cuda-9.2/nvvm/include -I /usr/local/cuda-9.2/extras/CUPTI/include"
  - CGO_LDFLAGS="${CGO_LDFLAGS} -L /usr/local/nvidia/lib64 -L /usr/local/cuda-9.2/nvvm/lib64 -L /usr/local/cuda-9.2/lib64 -L /usr/local/cuda-9.2/lib64/stubs -L /usr/local/cuda-9.2/targets/x86_64-linux/lib/stubs/ -L /usr/local/cuda-9.2/lib64/stubs -L /usr/local/cuda-9.2/extras/CUPTI/lib64"
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
- cd ${TRAVIS_BUILD_DIR}
- dep ensure -v
- rm -fr vendor/github.com/Sirupsen
- find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
- go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
