language: go
cache:
  apt: true
matrix:
  include:
    - go: 1.12.x
    - go: tip
  allow_failures:
    - go: tip
dist: xenial
sudo: false
addons:
  apt:
    sources:
      - sourceline: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64
          /
        key_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
      - sourceline:
          deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64
          /
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libopenblas-dev
      - libgsl0-dev
      - liblapacke-dev
      - google-perftools
      - libgoogle-perftools-dev
      - graphviz
      - cmake
      - libmicrohttpd-dev
      - libssl-dev
      - libpci-dev
      - libhwloc-dev
      - libnuma-dev
      - libnccl2
      - cuda-cudart-dev-10-1
      - cuda-libraries-dev-10-1
      - cuda-misc-headers-10-1
      - cuda-nvml-dev-10-1
      - cuda-nvtx-10-1
      - cuda-cupti-10-1
      - libcudnn7
      - libcudnn7-dev
env:
  global:
    - CXX=g++-6
    - CC=gcc-6
    - CUDACXX=/usr/local/cuda-10.1/bin/nvcc
    - LD_LIBRARY_PATH=/usr/local/nvidia/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    - LD_LIBRARY_PATH=/usr/local/cuda-10.1/nvvm/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    - LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    - LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64/stubs${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    - LD_LIBRARY_PATH=/usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/:+:${LD_LIBRARY_PATH}}
    - LD_LIBRARY_PATH=/usr/local/cuda-10.1/extras/CUPTI/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    - PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
    - GODEBUG=cgocheck=0
    - CGO_CFLAGS="${CGO_CFLAGS} -I /usr/local/cuda-10.1/include -I/usr/local/cuda-10.1/nvvm/include -I /usr/local/cuda-10.1/extras/CUPTI/include"
    - CGO_LDFLAGS="${CGO_LDFLAGS} -L /usr/local/nvidia/lib64 -L /usr/local/cuda-10.1/nvvm/lib64 -L /usr/local/cuda-10.1/lib64 -L /usr/local/cuda-10.1/lib64/stubs -L /usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/ -L /usr/local/cuda-10.1/lib64/stubs -L /usr/local/cuda-10.1/extras/CUPTI/lib64"
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v .
